apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: hellohttp
    labels:
        app: hellohttp
spec:
    selector:
        matchLabels:
            app: hellohttp
    replicas: 2
    template: 
        metadata:
            labels:
                app: hellohttp
        spec:
            volumes:
                - name: config
                  configMap:
                    name: testconfig
            containers:
            - image: jmliber/hello3:0.0.13
              name: hellohttp
              volumeMounts:
                - name: config
                  mountPath: /config
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: mysql-1593208582
                        key: mysql-root-password
                - name: MYSQL_HOST
                  value: "mysql"
              
