apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: hellobazel
    labels:
        app: hellobazel
spec:
    selector:
        matchLabels:
            app: hellobazel
    replicas: 1
    template: 
        metadata:
            labels:
                app: hellobazel
        spec:
            containers:
            - image: gcr.io/hellohttp-a/hello-bazel:50
              name: hellobazel
              env:
                - name: MYSQL_HOST
                  value: "mysql"
              
