apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: hellohttp
    labels:
        app: hellohttp
spec:
    selector:
        matchLabels:
            app: hellohttp
    replicas: 2
    template: 
        metadata:
            labels:
                app: hellohttp
        spec:
            containers:
            - image: jmliber/hello2:1.19
              name: hellohttp
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: mysql-1593208582
                        key: mysql-root-password
