apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: hellohttp
    labels:
        app: hellohttp
spec:
    selector:
        matchLabels:
            app: hellohttp
    replicas: 1
    template: 
        metadata:
            labels:
                app: hellohttp
        spec:
            containers:
            - image: gcr.io/hellohttp-a/hello2:1.0.168
              name: hellohttp
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: mysql-1593208582
                        key: mysql-root-password
                - name: MYSQL_HOST
                  value: "mysql"
              
