apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: hellohttp-backend
    labels:
        app: hellohttp-backend
spec:
    selector:
        matchLabels:
            app: hellohttp-backend
    replicas: 2
    template: 
        metadata:
            labels:
                app: hellohttp-backend
        spec:
            volumes:
                - name: vol1
                  persistentVolumeClaim:
                    claimName: task-pv-claim
            containers:
            - image: jmliber/hellohttp-backend:0.5
              name: hellohttp-backend
              volumeMounts:
                - mountPath: "/mnt/vol/foo"
                  name: vol1
