apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: wedding
    labels:
        app: wedding
spec:
    selector:
        matchLabels:
            app: wedding
    template: 
        metadata:
            labels:
                app: wedding
        spec:
          containers:
          - image: jmliber/wedding:0.1
            name: wedding
              
