apiVersion: v1
kind: Service
metadata:
  name: hellohttp
spec:
    type: LoadBalancer
    selector:
        app: hellohttp
    ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
