version: 2.1
orbs:
  docker: circleci/docker@1.0
  gcp-auth: circleci/gcp-binary-authorization@0.5.2
  gcp-gke: circleci/gcp-gke@1.0.4
  gcr: circleci/gcp-gcr@0.7.1
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  build-and-deploy: 
    environment:
        GOOGLE_PROJECT_ID: hellohttp-a
        GOOGLE_COMPUTE_ZONE: us-central1-c
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - gcr/gcr-auth 
      - setup_remote_docker
      - run: 
          command: |
            ls -al 
            pwd
      - checkout
      - docker/build:
          image: gcr.io/hellohttp-a/hello2
          tag: 1.0.<< pipeline.number >>
          path: docker/hello2
          docker-context: /home/circleci/project
      - gcr/push-image:
          image: hello2
          tag: 1.0.<< pipeline.number >> 
      - kube-orb/install 
#      - gcp-gke/rollout-image:
#          cluster: hellohttp-b 
#          container: hellohttp
#          deployment: hellohttp
#          image: gcr.io/hellohttp-a/hello2
#          tag: 1.0.<< pipeline.number >> 

#  deploy-job:
#    environment:
#        GOOGLE_PROJECT_ID: hellohttp-a
#        GOOGLE_COMPUTE_ZONE: us-central1-c
#    docker:
#      - image: circleci/buildpack-deps:stretch
#    steps:
#      - gcr/gcr-auth 
#      - setup_remote_docker
#      - kube-orb/install 
#      - gcp-gke/rollout-image:
#          cluster: hellohttp-b 
#          container: hellohttp
#          deployment: hellohttp
#          image: gcr.io/hellohttp-a/hellohttp
#          tag: 1.0.<< pipeline.number >> 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy
#          filters: # only deploy a tagged release
#            tags:
#                only: /^([0-9]+)$/