apiVersion: v1
kind: Service
metadata:
  name: helloload
  annotations:
      cloud.google.com/load-balancer-type: "Internal"
spec:
    type: LoadBalancer
    selector:
        app: helloload
    ports:
    - port: 80
