apiVersion: v1
kind: Service
metadata:
  name: hellohttp
  annotations:
      cloud.google.com/load-balancer-type: "Internal"
spec:
    type: LoadBalancer
    selector:
        app: hellohttp
    ports:
    - port: 8080
