apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hellohttp-in
spec:
    backend:
        serviceName: hellohttp
        servicePort: 8080
    rules:
    - http:
        paths:
        - path: /api
          backend:
            serviceName: hellohttp-backend
            servicePort: 80
        - path: /load
          backend:
            serviceName: helloload
            servicePort: 80
