apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hellohttp-in
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
    - http:
        paths:
        - path: /api
          backend:
            serviceName: hellohttp-backend
            servicePort: 80
        - path: /load
          backend:
            serviceName: helloload
            servicePort: 80
        - path: /wedding
          backend:
            serviceName: wedding
            servicePort: 80
    backend:
        serviceName: hellohttp
        servicePort: 8080
