apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hellohttp-in
spec:
    backend:
        serviceName: hellohttp
        servicePort: 8080
    rules:
    - http:
        paths:
        - path: /foo
          backend:
            serviceName: hellohttp-foo
            servicePort: 8080
