apiVersion: v1
kind: Secret
metadata:
  name: mysql-1593208582
  namespace: default
  labels:
    app: mysql-1593208582
    chart: "mysql-1.6.4"
    release: "mysql-1593208582"
    heritage: "Helm"
type: Opaque
data:
  
  
  mysql-root-password: "cXRUSU85M2owTQ=="
  
  
  
  
  mysql-password: "R1JMS2JFMFJxUA=="
