name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull dependencies
      run: go get github.com/go-sql-driver/mysql

    - name: Build
      run: go build ./src/*.go

    - name: Test
      run: go test -v ./...
