name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      IMAGE: gcr.io/hellohttp-a/hello-bazel

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bazel run --incompatible_restrict_string_escapes=false //src/hello:hello

    - name: Test
      run: go test -v ./...
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: hellohttp
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        export_default_credentials: true
    
    - name: Auth
      run: gcloud auth configure-docker --quiet

    - name: Cluster Authentication
      run: |
        gcloud container clusters get-credentials hellobazel-cluster --zone us-east1-d --project hellohttp-a
    
    - name: Tag Image
      run: docker tag bazel/src/hello:hello $IMAGE:$GITHUB_RUN_NUMBER
    
    - name: Push Image
      run: docker push $IMAGE:$GITHUB_RUN_NUMBER
    
    # Set up kustomize
    - name: Set up Kustomize
      run: |
        curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
      
    - name: Update Image
      run: |
        ./kustomize edit set image $IMAGE:$GITHUB_RUN_NUMBER
        ./kustomize build . | kubectl apply -f -

    - name: Get Status
      run: |
        kubectl rollout status deployment/hellobazel
        kubectl get services -o wide

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        msg_minimal: true
        
      
