name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bazel run --incompatible_restrict_string_escapes=false //src/hello:hello
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: go test -v ./...
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: hellohttp
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        export_default_credentials: true
    
    - name: Auth
      run: gcloud auth configure-docker --quiet
    
    - name: Tag Image
      run: docker tag bazel/src/hello:hello gcr.io/hellohttp-a/hello-bazel:1.0
    
    - name: Push Image
      run: docker push gcr.io/hellohttp-a/hello-bazel:1.0